# Generated by Django 2.2.5 on 2019-11-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
